import { createFileRoute } from "@tanstack/react-router";
import { abs } from "@/lib/seo";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Getyourcodes" },
      {
        name: "description",
        content:
          "Learn how Getyourcodes, operated by Pixorads, handles account information, site activity and Dealio messages, and how to contact us about privacy.",
      },
      { property: "og:title", content: "Privacy Policy — Getyourcodes" },
      {
        property: "og:description",
        content:
          "How Getyourcodes handles information when you use our coupon discovery service, your account and Dealio.",
      },
      { property: "og:url", content: abs("/privacy") },
      { name: "robots", content: "index,follow" },
    ],
    links: [{ rel: "canonical", href: abs("/privacy") }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
      <header>
        <h1 className="font-display text-3xl font-bold sm:text-4xl">Privacy Policy</h1>
        <p className="mt-3 text-sm text-muted-foreground">Last updated: 5 October 2026</p>
        <p className="mt-6 leading-relaxed text-muted-foreground">
          Getyourcodes is owned and operated by Pixorads. This policy explains how information may
          be processed when you browse offers, use an account or interact with our services.
        </p>
      </header>

      <div className="mt-10 space-y-8 leading-relaxed text-muted-foreground">
        <section>
          <h2 className="font-display text-xl font-semibold text-foreground">
            Information we may process
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>
              Account and authentication information, such as your email address and user profile.
            </li>
            <li>Saved stores and coupons, and account preferences.</li>
            <li>Your email address when you subscribe to our newsletter.</li>
            <li>Search activity and interactions with coupon, deal and merchant links.</li>
            <li>Chat messages and history when you use Dealio, our AI shopping assistant.</li>
            <li>
              Technical and usage information generated by site operation, such as browser details,
              request information and error logs.
            </li>
            <li>Information you send us through support or contact channels.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-foreground">
            How information is used
          </h2>
          <p className="mt-3">
            We use information to operate accounts and saved items, provide search and Dealio
            features, deliver requested newsletters, understand offer interactions, respond to
            questions and maintain the security and performance of the service. Please avoid sharing
            sensitive personal information in Dealio messages.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-foreground">
            Service providers and merchant links
          </h2>
          <p className="mt-3">
            Information may be processed by hosting, database and authentication providers that
            support the site; email delivery services for communications; and AI service providers
            when you use Dealio. Analytics or performance tools may process usage information if
            enabled or configured. Affiliate networks and merchants may receive referral and
            interaction information when you follow merchant links, including information used to
            attribute qualifying activity.
          </p>
          <p className="mt-3">
            Purchases take place on merchant websites. Getyourcodes does not itself process the
            merchant checkout. Those websites and other third-party services have their own privacy
            practices, which you should review when using them.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-foreground">
            Cookies, sessions and local storage
          </h2>
          <p className="mt-3">
            Authentication and session technologies, local storage and cookies may be used to keep
            you signed in, remember preferences and support site features. Your browser lets you
            manage cookies and stored data; blocking or clearing them may affect these features.
            Merchant websites may also use their own cookies and tracking technologies.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-foreground">
            Retention and security
          </h2>
          <p className="mt-3">
            Information may be retained as reasonably necessary to operate the service, maintain
            security, resolve issues and meet legal obligations. We use reasonable security
            measures, but no online system is guaranteed to be completely secure.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-foreground">
            Questions, requests and updates
          </h2>
          <p className="mt-3">
            For privacy questions or requests concerning your information, contact{" "}
            <a
              className="text-primary underline underline-offset-4"
              href="mailto:partner@pixorads.com"
            >
              partner@pixorads.com
            </a>
            . We may need to verify your identity to handle an account-related request. This policy
            may be updated as the service changes; the date above identifies the latest revision.
          </p>
        </section>
      </div>
    </article>
  );
}
