/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AdminStoresNewRouteImport } from './routes/admin.stores.new'
import { Route as AdminStoresIdRouteImport } from './routes/admin.stores.$id'
import { Route as AdminCouponsNewRouteImport } from './routes/admin.coupons.new'
import { Route as AdminCouponsIdRouteImport } from './routes/admin.coupons.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminStoresNewRoute = AdminStoresNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminStoresRoute,
} as any)
const AdminStoresIdRoute = AdminStoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStoresRoute,
} as any)
const AdminCouponsNewRoute = AdminCouponsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCouponsRoute,
} as any)
const AdminCouponsIdRoute = AdminCouponsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCouponsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/coupons/$id': typeof AdminCouponsIdRoute
  '/admin/coupons/new': typeof AdminCouponsNewRoute
  '/admin/stores/$id': typeof AdminStoresIdRoute
  '/admin/stores/new': typeof AdminStoresNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/coupons/$id': typeof AdminCouponsIdRoute
  '/admin/coupons/new': typeof AdminCouponsNewRoute
  '/admin/stores/$id': typeof AdminStoresIdRoute
  '/admin/stores/new': typeof AdminStoresNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/coupons/$id': typeof AdminCouponsIdRoute
  '/admin/coupons/new': typeof AdminCouponsNewRoute
  '/admin/stores/$id': typeof AdminStoresIdRoute
  '/admin/stores/new': typeof AdminStoresNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/account'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/api/chat'
    | '/admin/'
    | '/admin/coupons/$id'
    | '/admin/coupons/new'
    | '/admin/stores/$id'
    | '/admin/stores/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/account'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/api/chat'
    | '/admin'
    | '/admin/coupons/$id'
    | '/admin/coupons/new'
    | '/admin/stores/$id'
    | '/admin/stores/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/api/chat'
    | '/admin/'
    | '/admin/coupons/$id'
    | '/admin/coupons/new'
    | '/admin/stores/$id'
    | '/admin/stores/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/stores/new': {
      id: '/admin/stores/new'
      path: '/new'
      fullPath: '/admin/stores/new'
      preLoaderRoute: typeof AdminStoresNewRouteImport
      parentRoute: typeof AdminStoresRoute
    }
    '/admin/stores/$id': {
      id: '/admin/stores/$id'
      path: '/$id'
      fullPath: '/admin/stores/$id'
      preLoaderRoute: typeof AdminStoresIdRouteImport
      parentRoute: typeof AdminStoresRoute
    }
    '/admin/coupons/new': {
      id: '/admin/coupons/new'
      path: '/new'
      fullPath: '/admin/coupons/new'
      preLoaderRoute: typeof AdminCouponsNewRouteImport
      parentRoute: typeof AdminCouponsRoute
    }
    '/admin/coupons/$id': {
      id: '/admin/coupons/$id'
      path: '/$id'
      fullPath: '/admin/coupons/$id'
      preLoaderRoute: typeof AdminCouponsIdRouteImport
      parentRoute: typeof AdminCouponsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminCouponsRouteChildren {
  AdminCouponsIdRoute: typeof AdminCouponsIdRoute
  AdminCouponsNewRoute: typeof AdminCouponsNewRoute
}

const AdminCouponsRouteChildren: AdminCouponsRouteChildren = {
  AdminCouponsIdRoute: AdminCouponsIdRoute,
  AdminCouponsNewRoute: AdminCouponsNewRoute,
}

const AdminCouponsRouteWithChildren = AdminCouponsRoute._addFileChildren(
  AdminCouponsRouteChildren,
)

interface AdminStoresRouteChildren {
  AdminStoresIdRoute: typeof AdminStoresIdRoute
  AdminStoresNewRoute: typeof AdminStoresNewRoute
}

const AdminStoresRouteChildren: AdminStoresRouteChildren = {
  AdminStoresIdRoute: AdminStoresIdRoute,
  AdminStoresNewRoute: AdminStoresNewRoute,
}

const AdminStoresRouteWithChildren = AdminStoresRoute._addFileChildren(
  AdminStoresRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
